blueprints/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from models import User, db

auth_bp = Blueprint("auth", __name__)


@auth_bp.get("/login")
def login_get():
    if current_user != None and current_user.is_authenticated:
        return redirect(url_for("index"))
    return render_template("login.html")


@auth_bp.post("/login")
def login_post():
    user = User.query.filter_by(username=request.form.get("username")).first()
    if user != None and user.check_password(request.form.get("password")):
        login_user(user=user)
        return redirect(url_for("index"))
    flash("Incorrect username or password.")
    return render_template("login.html")


@auth_bp.get("/register")
def register_get():
    if current_user != None and current_user.is_authenticated:
        return redirect(url_for("index"))
    return render_template("register.html")


@auth_bp.post("/register")
def register_post():
    user = User.query.filter_by(username=request.form.get("username")).first()
    if user != None:
        flash("That username is already taken - choose another one...")
    else:
        if request.form.get("password") == request.form.get("confirm_password"):
            new_user = User(
                request.form.get("name"),
                request.form.get("username"),
                request.form.get("password"),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for("index"))
        else:
            flash("Passwords don't match...")
    return render_template("register.html")


@auth_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index"))

blueprints/paycheck_calculator.py
from flask import Blueprint, request, render_template, make_response, current_app
from flask_login import login_required
import requests

from models import User, db


class PayrateMath:
    def __init__(self, base_payrate, shift_diff_payrate, overtime_payrate):
        self.base_payrate = base_payrate
        self.shift_diff_payrate = shift_diff_payrate
        self.overtime_ratio = overtime_payrate

    def get_gross_pay_str(self, payrates: list) -> str:
        gross_pay = 0.0

        for rate in payrates:
            gross_pay += float(rate["payRate"]) * float(rate["hours"])

        return f"{gross_pay:.2f}"


pay_calc_bp = Blueprint("PaycheckCalculator", __name__)


@pay_calc_bp.get("/paycheck-calculator")
@login_required
def paycheck_calculator():
    return render_template("old-paycheck-calculator.html")


@pay_calc_bp.post("/paycheck-calculator")
@login_required
def api_paycheck_calculator():

    req_json = request.json

    url = "https://calculators.symmetry.com/api/calculators/salary"
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
        "Pcc-Api-Key": current_app.config["PAYCHECK_CALC_API_KEY"],
    }

    USER_ID = req_json.get("user_id")

    BASE_PAYRATE = float(req_json.get("base_payrate"))
    SHIFT_DIFF_PAYRATE = float(req_json.get("shiftdiff_payrate"))
    OVERTIME_PAYRATE = BASE_PAYRATE * 1.5

    BASE_HOURS = float(req_json.get("base_hours"))
    SHIFT_DIFF_HOURS = float(req_json.get("shiftdiff_hours"))
    OVERTIME_HOURS = float(req_json.get("overtime_hours"))

    BENEFITS_COST = float(req_json.get("benefit_cost"))
    RETIREMENT_COST = float(req_json.get("retirement_cost"))

    payrates = [
        {"payRate": str(BASE_PAYRATE), "hours": str(BASE_HOURS)},
        {"payRate": str(SHIFT_DIFF_PAYRATE), "hours": str(SHIFT_DIFF_HOURS)},
        {"payRate": str(OVERTIME_PAYRATE), "hours": str(OVERTIME_HOURS)},
    ]

    req_handler = PayrateMath(BASE_PAYRATE, SHIFT_DIFF_PAYRATE, OVERTIME_PAYRATE)
    gross_pay_str = req_handler.get_gross_pay_str(payrates)

    user = User.query.filter_by(id=USER_ID).first()

    if user != None:
        user.base_payrate = BASE_PAYRATE
        user.shift_diff_payrate = SHIFT_DIFF_PAYRATE
        user.benefits_cost = BENEFITS_COST
        user.retirement_cost = RETIREMENT_COST
        db.session.commit()

    RETIREMENT_DOLLARS = float(gross_pay_str) * RETIREMENT_COST / 100
    BENEFITS_COST += RETIREMENT_DOLLARS

    payload = {
        "grossPay": gross_pay_str,
        "grossPayType": "PAY_PER_PERIOD",
        "grossPayYTD": "0",
        "payFrequency": "BI_WEEKLY",
        "w42020": True,
        "federalFilingStatusType2020": "SINGLE",
        "federalFilingStatusType": "SINGLE",
        "federalAllowances": "0",
        "twoJobs2020": "false",
        "dependents2020": "0",
        "otherIncome2020": "0",
        "deductions2020": "0",
        "additionalFederalWithholding": "0",
        "roundFederalWithholding": "false",
        "exemptFederal": "false",
        "exemptFica": "false",
        "exemptMedicare": "false",
        "checkDate": 1737149475000,
        "rates": payrates,
        "state": "PA",
        "stateInfo": {
            "parms": [
                {"name": "stateExemption", "value": False},
                {"name": "additionalStateWithholding", "value": "0"},
                {"name": "MOST_RECENT_WH", "value": "0.0"},
                {"name": "42-000-0000-SUI-000", "value": True},
                {"name": "PA_WAGES_ONLY", "value": "TRUE"},
            ],
            "local": {
                "address1": "270 Midway Road",
                "address2": "",
                "city": "Bethel",
                "zip": "19507",
                "zip4": "",
                "resident": False,
                "exempt": False,
            },
        },
        "voluntaryDeductions": [
            {
                "deductionName": "Benefits",
                "deductionAmount": str(BENEFITS_COST),
                "deductionMethodType": "FIXED_AMOUNT",
                "exemptFederal": False,
                "exemptFica": False,
                "exemptState": False,
                "exemptLocal": False,
                "benefitType": "_Custom",
                "ytdAmount": 0,
            }
        ],
    }

    response = requests.post(url, headers=headers, json=payload)

    return response.json().get("content")

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
        <title>Finance Tracker - {% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="{{ url_for('static', filename='reset.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='daisyui.css') }}">

        <script type="text/javascript" src="{{ url_for('static', filename='jquery-3.7.1.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='tailwindcss.js') }}"></script>
        {% block head %}{% endblock %}
    </head>
    <body class="bg-zinc-800">
        <div class="navbar bg-zinc-900">            
            <div class="flex-1">
                <a class="btn btn-ghost text-xl" href="{{ url_for('index') }}">
                    MyFi
                </a>
            </div>
            <div class="flex-none">
                <ul class="menu menu-horizontal px-1">
                {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for("PaycheckCalculator.paycheck_calculator") }}">
                            Paycheck Calc
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for("testing") }}">
                            Testing
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for("get_transactions") }}">
                            Transactions
                        </a>
                    </li>
                    <li>
                        <details>
                            <summary>{{ current_user.name }}</summary>
                            <ul class="bg-zinc-900 rounded-t-none p-2">
                                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                            </ul>
                        </details>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for('auth.register_get') }}">
                            Register
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.login_get') }}">
                            Log In
                        </a>
                    </li>
                {% endif %}
                </ul>
            </div>
        </div>
        {% block body %}
        {% endblock %}
    </body>
</html>

templates/css-testing.html
{% extends "base.html" %}

{% block title %}CSS Playground{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='testing.css') }}">
{% endblock %}

{% block body%}
{% endblock %}

templates/expenses.html
{% extends "base.html" %}

{% block title %}Expenses{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
<div class="banger-2">
    <div class="flex-center-contents">
        <table>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Day of Month</th>
            </tr>
            {% for expense in current_user.expenses %}
                <tr>
                    <td>{{ expense.name }}</td>
                    <td>{{ expense.amount }}</td>
                    <td>{{ expense.day_of_month }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="form-container flex-center-contents">
        <form action="" method="POST">
            <div class="row">
                <div class="field-input">
                    <label for="name">Name</label>
                    <input autocomplete="off" type="text" name="name" id="name" placeholder="expense name">
                </div>
                <div class="field-input">
                    <label for="amount">Amount</label>
                    <input autocomplete="off" type="float" name="amount" id="amount" placeholder="0.00">
                </div>
            </div>
            <div class="row">
                <div class="field-input">
                    <label for="day_of_month">Day of Month</label>
                    <input autocomplete="off" type="text" name="day_of_month" id="day_of_month" placeholder="15">
                </div>
                <div class="field-input">
                    <label for="payment_source">Payment Source</label>
                    <input autocomplete="off" type="text" name="payment_source" id="payment_source" placeholder="1">
                </div>
            </div>
            <div class="row">
                <div class="field-extended-button">
                    <input class="button" type="submit" value="Create Expense">
                </div>
            </div>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        </form>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
{% endblock %}

{% block body %}
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
{% endblock %}

{% block body %}
<div class="form-container pt-40 flex justify-center align-center">
    <form class="bg-zinc-900" action="" method="POST">
        <div class="row">
            <div class="field-input">
                <label for="username">Username</label>
                <input autocomplete="off" type="text" name="username" id="username" placeholder="user123" value="{{ request.form.get('username', '') }}">
            </div>
            <div class="field-input">
                <label for="password">Password</label>
                <input autocomplete="off" type="password" name="password" id="password" placeholder="pass123">
            </div>
        </div>
        <div class="row">
            <div class="field-extended-button">
                <input class="button" type="submit" value="Login">
            </div>
        </div>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    </form>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <article class="message is-warning">
                    <div class="message-body">
                        {{ message }}
                    </div>
                </article>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>

{% endblock %}

templates/old-paycheck-calculator.html
{% extends "base.html" %}

{% block title %}Old Paycheck Calculator{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
<script type='text/javascript'>
const USER_ID = {{current_user.id}};
</script>
<script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
{% endblock %}

{% block body %}

<div class="form-container pt-40 flex justify-center align-center">
    <form class="bg-zinc-900" id="paycheck-calculator-form">
        <div class="row">
            <div class="field-input">
                <label for="base_payrate">Hourly Pay</label>
                <input autocomplete="off" placeholder="0.00" type="float" name="base_payrate" id="base_payrate" value="{{ current_user.base_payrate }}" />
            </div>
            <div class="field-input">
                <label for="shiftdiff_payrate">Shift Diff Pay</label>
                <input autocomplete="off" placeholder="0.00" type="float" name="shiftdiff_payrate" id="shiftdiff_payrate" value="{{ current_user.shift_diff_payrate }}" />
            </div>
        </div>
        <div class="row">
            <div class="field-input">
                <label for="benefit_cost">Benefits</label>
                <input autocomplete="off" placeholder="0.00" type="float" name="benefit_cost" id="benefit_cost" value="{{ current_user.benefits_cost }}"/>
            </div>
            <div class="field-input">
                <label for="retirement_cost">Retirement %</label>
                <input autocomplete="off" placeholder="0.0" type="float" name="retirement_cost" id="retirement_cost" value="{{ current_user.retirement_cost }}"/>
            </div>
        </div>
        <div class="row">
            <div class="field-input">
                <label for="base_hours">Regular Hours</label>
                <input autocomplete="off" placeholder="0.00" type="float" name="base_hours" id="base_hours" value="0.0" />
            </div>
            <div class="field-input">
                <label for="shiftdiff_hours">Shift Diff Hours</label>
                <input autocomplete="off" placeholder="0.00" type="float" name="shiftdiff_hours" id="shiftdiff_hours" value="0.0" />
            </div>
            <div class="field-input">
                <label for="overtime_hours">OT / HOL Hours</label>
                <input autocomplete="off" placeholder="0.00" type="float" name="overtime_hours" id="overtime_hours" value="0.0" />
            </div>
        </div>
        <div class="row">
            <div class="field-extended-button">
                <input class="button" type="submit" value="Calculate"/>
            </div>
        </div>
        <div class="row">
            <div class="field">
                <p style="text-align: center; width: 100%;">Gross Pay</p>
                <p style="text-align: center; width: 100%; font-weight: bold;">$<span id="grosspay">0.00</span></p>
            </div>
            <div class="field">
                <p style="text-align: center; width: 100%;">Net Pay</p>
                <p style="text-align: center; width: 100%; font-weight: bold;">$<span id="netpay">0.00</span></p>
            </div>
            <div class="field">
                <p style="text-align: center; width: 100%;">Withheld</p>
                <p style="text-align: center; width: 100%; font-weight: bold;"><span id="withheld">0.0</span>%</p>
            </div>
        </div>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" id="csrf_token">
    </form>
</div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
{% endblock %}

{% block body %}
<div class="form-container pt-40 flex justify-center align-center">
    <form class="bg-zinc-900" action="" method="POST">
        <div class="row">
            <div class="field-input">
                <label for="name">Name</label>
                <input autocomplete="off" placeholder='firstname' type="text" name="name" id="name" value="{{ request.form.get('name', '') }}">
            </div>
            <div class="field-input">
                <label for="username">Username</label>
                <input autocomplete="off" placeholder='user123' type="text" name="username" id="username" value="{{ request.form.get('username', '') }}">
            </div>
        </div>
        <div class="row">
            <div class="field-input">
                <label for="password">Password</label>
                <input autocomplete="off" placeholder='pass123' type="password" name="password" id="password">
            </div>
            <div class="field-input">
                <label for="confirm_password">Confirm Pass</label>
                <input autocomplete="off" placeholder='pass123' type="password" name="confirm_password" id="confirm_password">
            </div>
        </div>
        <div class="row">
            <div class="field-extended-button">
                <input class="button" type="submit" value="Register">
            </div>
        </div>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    </form>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <article class="message is-warning">
                    <div class="message-body">
                        {{ message }}
                    </div>
                </article>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
{% endblock %}

templates/testing.html
{% extends "base.html" %}

{% block title %}CSS Playground{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='testing.css') }}">
{% endblock %}

{% block body%}
{% endblock %}

templates/transactions.html
{% extends "base.html" %}

{% block title %}Recurring Transactions{% endblock %}

{% block head %}
<script type="text/javascript" src="{{ url_for('static', filename='transactions.js') }}"></script>
{% endblock %}

{% block body %}
<div class="overflow-x-auto w-full max-w-7xl pt-40 flex flex-col justify-center align-center mx-auto">
    <div class="flex w-full justify-end mb-10">
        <button class="btn" onclick="my_modal_1.showModal()">Add</button>
        <button class="btn ml-4" onclick="my_modal_2.showModal()">Delete All</button>
        <dialog id="my_modal_1" class="modal">
            <div class="form-container form-in-modal">
                <form class="bg-zinc-900" id="transaction-add-form" method="POST">
                    <div class="row">
                        <div class="field-input">
                            <label for="name">Name</label>
                            <input autocomplete="off" type="text" name="name" id="name" placeholder="expense name">
                        </div>
                        <div class="field-input">
                            <label for="amount">Amount</label>
                            <input autocomplete="off" type="float" name="amount" id="amount" placeholder="0.00">
                        </div>
                    </div>
                    <div class="row">
                        <div class="field-input">
                            <label for="day_of_month">Day of Month</label>
                            <input autocomplete="off" type="text" name="day_of_month" id="day_of_month" placeholder="15">
                        </div>
                        <div class="field-checkbox">
                            <label for="is_credit">Is Credit</label>
                            <input autocomplete="off" class="checkbox checkbox-sm" type="checkbox" name="is_credit" id="is_credit">
                        </div>
                    </div>
                    <div class="row">
                        <div class="field-extended-button">
                            <input class="button" type="submit" value="Create Expense">
                        </div>
                    </div>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>
            </div>
            <form method="dialog" class="modal-backdrop">
              <button>close</button>
            </form>
        </dialog>
        <dialog id="my_modal_2" class="modal">
            <div class="modal-box">
                <form id="transaction-del-form">
                    <input type="submit" class="btn btn-error" value="Confirm">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>
            </div>
            <form method="dialog" class="modal-backdrop">
                <button>close</button>
            </form>
        </dialog>
        <dialog id="my_modal_3" class="modal">
            <div class="form-container form-in-modal">
                <form class="bg-zinc-900" id="transaction-update-form">
                    <div class="row">
                        <div class="field-input">
                            <label for="name">Name</label>
                            <input autocomplete="off" type="text" name="name" id="name" placeholder="expense name">
                        </div>
                        <div class="field-input">
                            <label for="amount">Amount</label>
                            <input autocomplete="off" type="float" name="amount" id="amount" placeholder="0.00">
                        </div>
                    </div>
                    <div class="row">
                        <div class="field-input">
                            <label for="day_of_month">Day of Month</label>
                            <input autocomplete="off" type="text" name="day_of_month" id="day_of_month" placeholder="15">
                        </div>
                        <div class="field-checkbox">
                            <label for="is_credit">Is Credit</label>
                            <input autocomplete="off" class="checkbox checkbox-sm" type="checkbox" name="is_credit" id="is_credit">
                        </div>
                    </div>
                    <div class="row">
                        <div class="field-button">
                            <input class="button" type="submit" value="Update">
                        </div>
                        <div class="field-button">
                            <input class="button" type="submit" value="Delete">
                        </div>
                    </div>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>
            </div>
            <form method="dialog" class="modal-backdrop">
              <button>close</button>
            </form>
        </dialog>
    </div> 
    <table class="table w-full">
        <thead>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Day of Month</th>
                <th>Is Credit</th>
            </tr>
        </thead>
        <tbody id="transactions-tbody">
        {% for transaction in current_user.recurring_transactions %}
            <tr class="hover">
                <td>{{ transaction.name }}</td>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.day_of_month }}</td>
                <td>{{ transaction.is_credit }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}